### ISSUE TITLE
Decode Fail Bug

### ISSUE THREAD

**Issue by zhongyizengzy** [pkuvcl/davs2#6] opened 2018-11-04 06:02 UTC
root@iZuf6a76txemsleel0sc9hZ:~/avs2# davs2 -i 电影-动作片_镜头切换频繁_3mins_avs_cqp_13_0_16.avs -o 电影-动作片_镜头切换频繁_3mins_avs_cqp_13_0_16.yuv --threads=1
davs2 -i 电影-动作片_镜头切换频繁_3mins_avs_cqp_13_0_16.avs -o 电影-动作片_镜头切换频繁_3mins_avs_cqp_13_0_16.yuv --threads=1 

--------------------------------------------------
 AVS2 file       : 电影-动作片_镜头切换频繁_3mins_avs_cqp_13_0_16.avs
 Reference file  : (null)
 Output file     : 电影-动作片_镜头切换频繁_3mins_avs_cqp_13_0_16.yuv
--------------------------------------------------
[davs2 info]: davs2: 1.5.131 1db2b48c28e24f20.8, 2018-10-31 12:51:42
[davs2 info]: CPU Capabilities:  MMX2 SSE2Fast SSSE3 SSE4.2 AVX AVX2 FMA3 LZCNT BMI2
[davs2 info]: Manager 7fa76003f020: using 1 thread(s): 1(frame/AEC)+0(pool/REC), 2 tasks
[davs2 info]: Manager 7fa76003f020: Sequence Resolution: 1920x1080.
  Sequence size: 1920x1080; BitDepth: 8/8, FrameRate: 30.000 Hz

[davs2 debug]: Dec[ 1] 7fa7600443c0: discontinuous COI (prev: 137 --> curr: 137).
davs2: /root/davs2/source/common/decoder.cc:294: void task_send_picture_to_output_list(davs2_t*, davs2_outpic_t*): Assertion `curr == NULL || curr->frame->i_poc > pic->frame->i_poc' failed.
Aborted: 4485/4502,  fps: 40.3, LeftTime:    0.422 sec

**Comment by luofalei** [comment] 2018-11-11 11:29
This was caused by a bug in the `xavs2` encoder and has been fixed in 
https://github.com/pkuvcl/xavs2/issues/10

Thanks.

**Closed by luofalei** 2018-11-11 11:29 UTC
